name: cathywang
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.2303108675405383
  saturation: 0.31047878065146506
  rhythmicContrast: 0.5
purpose: []
